<a href="https://colab.research.google.com/github/gabrielccr-555/self-service-analytics/blob/main/Aula2_SSA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pandas
Começaremos a falar sobre o processo de ingestão, ou seja, recebimento desses dados, envolvendo também a limpeza.

Pandas é uma biblioteca de Python utilizada para leitura, limpeza, transformação e análise de dados.
- Trabalha com dados tabulares

In [ ]:
import pandas as pd

O Pandas trabalha com algumas estruturas:
## Series
É um vetor ou uma matriz de única dimensão. Pode ser vista como uma coluna de uma tabela ou uma lista de valores indexados.

In [ ]:
notas = pd.Series([8.5, 7.0, 9.0, 6.5])

In [ ]:
print(notas.mean())
print(notas.max())
print(notas.sum())
print(notas[0])

7.75
9.0
31.0
8.5

## Dataframe
Representa uma tabela com colunas e linhas. Várias transformações podem ser realizadas no DataFrame.

In [ ]:
dados = {
    "nome": ["Ana", "Bruno", "Carlos"],
    "idade": [20, 22, 21],
    "curso": ["SI", "CC", "SI"]
}

df = pd.DataFrame(dados)
df

     nome  idade curso
0     Ana     20    SI
1   Bruno     22    CC
2  Carlos     21    SI

In [ ]:
df["nome"]

0       Ana
1     Bruno
2    Carlos
Name: nome, dtype: object

Na maioria dos casos não estaremos criando dataframes na mão, é aqui que entra o processo de automação.

## Leitura CSV
Upload
- df = pd.read_csv("entrada.csv")

A quantidade de linhas e colunas carregadas está correta?
- df.shape

Observar visualmente problemas nos dados carregados
- df.head()

Finalmente, analisar a estrutura dos dados identificados (metadados)
- df.info()

Resumo com vários indicadores estatísticos

- df.describe()

In [ ]:
!wget https://raw.githubusercontent.com/esensato/ssa-2026-01/refs/heads/main/entrada.csv

--2026-03-02 23:09:33--  https://raw.githubusercontent.com/esensato/ssa-2026-01/refs/heads/main/entrada.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 688 [text/plain]
Saving to: ‘entrada.csv.1’

entrada.csv.1       100%[===================>]     688  --.-KB/s    in 0s

2026-03-02 23:09:34 (51.9 MB/s) - ‘entrada.csv.1’ saved [688/688]

In [ ]:
df = pd.read_csv("entrada.csv")
df

,id_pedido,id_cliente,nome,data,produto,quantidade,preco,total,sistema_origem
0,1001,C001,João Silva,2023-01-05,Notebook,1,3500.0,3500.0,ERP
1,1002,C002,Maria Souza,05/01/2023,Mouse,2,50.0,100.0,ERP
2,1003,C002,Maria Souza,2023/01/06,Mouse,2,50.0,100.0,API
3,1003,C002,Maria Souza,2023/01/06,Mouse,2,50.0,100.0,API
4,1004,NaN,Carlos Lima,2023-01-07,Teclado,0,120.0,120.0,Planilha
5,1005,C004,ANA PEREIRA,07-01-2023,Monitor,-,899.0,899.0,Planilha
6,1006,C005,Pedro Santos,2023-01-08,monitor,1,899.0,899.0,NaN
7,1007,C006,Pedro Santos,2023-01-08,Cadeira Gamer,1,1200.5,1200.5,ERP
8,1008,C006,Pedro SANTOS,2023-01-08,Cadeira Gamer,1,1200.5,1200.5,ERP
9,1009,C007,Marcos Oliveira,2023-01-08,Teclado,2,120.0,240.0,NaN

In [ ]:
# Metadado
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id_pedido       10 non-null     int64
 1   id_cliente      9 non-null      object
 2   nome            10 non-null     object
 3   data            10 non-null     object
 4   produto         10 non-null     object
 5   quantidade      10 non-null     object
 6   preco           10 non-null     float64
 7   total           10 non-null     float64
 8   sistema_origem  8 non-null      object
dtypes: float64(2), int64(1), object(6)
memory usage: 852.0+ bytes

In [ ]:
# Informações Estatísticas Rápidas
df.describe()

        id_pedido        preco        total
count    10.00000    10.000000    10.000000
mean   1004.80000   808.900000   835.900000
std       2.65832  1066.766162  1046.874417
min    1001.00000    50.000000   100.000000
25%    1003.00000    67.500000   105.000000
50%    1004.50000   509.500000   569.500000
75%    1006.75000  1125.125000  1125.125000
max    1009.00000  3500.000000  3500.000000

Também é possível refinar a leitura de dados no momento de carregamento do arquivo!

In [ ]:
# Remove os espaços
df["id_cliente"] = df["id_cliente"].str.strip()
df["produto"] = df["produto"].str.strip()
df["nome"] = df["nome"].str.strip()
df

,id_pedido,id_cliente,nome,data,produto,quantidade,preco,total,sistema_origem
0,1001,C001,João Silva,2023-01-05,Notebook,1,3500.0,3500.0,ERP
1,1002,C002,Maria Souza,05/01/2023,Mouse,2,50.0,100.0,ERP
2,1003,C002,Maria Souza,2023/01/06,Mouse,2,50.0,100.0,API
3,1003,C002,Maria Souza,2023/01/06,Mouse,2,50.0,100.0,API
4,1004,NaN,Carlos Lima,2023-01-07,Teclado,0,120.0,120.0,Planilha
5,1005,C004,ANA PEREIRA,07-01-2023,Monitor,-,899.0,899.0,Planilha
6,1006,C005,Pedro Santos,2023-01-08,monitor,1,899.0,899.0,NaN
7,1007,C006,Pedro Santos,2023-01-08,Cadeira Gamer,1,1200.5,1200.5,ERP
8,1008,C006,Pedro SANTOS,2023-01-08,Cadeira Gamer,1,1200.5,1200.5,ERP
9,1009,C007,Marcos Oliveira,2023-01-08,Teclado,2,120.0,240.0,NaN

In [ ]:
# Tratar o problema de case sensitive (maiúsculas / minúsculas)
df["nome"] = df["nome"].str.title()
df["produto"] = df["produto"].str.upper()
df["sistema_origem"] = df["sistema_origem"].str.lower()
df

,id_pedido,id_cliente,nome,data,produto,quantidade,preco,total,sistema_origem
0,1001,C001,João Silva,2023-01-05,NOTEBOOK,1,3500.0,3500.0,erp
1,1002,C002,Maria Souza,05/01/2023,MOUSE,2,50.0,100.0,erp
2,1003,C002,Maria Souza,2023/01/06,MOUSE,2,50.0,100.0,api
3,1003,C002,Maria Souza,2023/01/06,MOUSE,2,50.0,100.0,api
4,1004,NaN,Carlos Lima,2023-01-07,TECLADO,0,120.0,120.0,planilha
5,1005,C004,Ana Pereira,07-01-2023,MONITOR,-,899.0,899.0,planilha
6,1006,C005,Pedro Santos,2023-01-08,MONITOR,1,899.0,899.0,NaN
7,1007,C006,Pedro Santos,2023-01-08,CADEIRA GAMER,1,1200.5,1200.5,erp
8,1008,C006,Pedro Santos,2023-01-08,CADEIRA GAMER,1,1200.5,1200.5,erp
9,1009,C007,Marcos Oliveira,2023-01-08,TECLADO,2,120.0,240.0,NaN

In [ ]:
# Remover linhas com valor não definidos;
# Recriando o df eliminando registros onde a coluna id_cliente tem valores NaN
df = df.dropna(subset="id_cliente")
df

,id_pedido,id_cliente,nome,data,produto,quantidade,preco,total,sistema_origem
0,1001,C001,João Silva,2023-01-05,NOTEBOOK,1,3500.0,3500.0,erp
1,1002,C002,Maria Souza,05/01/2023,MOUSE,2,50.0,100.0,erp
2,1003,C002,Maria Souza,2023/01/06,MOUSE,2,50.0,100.0,api
3,1003,C002,Maria Souza,2023/01/06,MOUSE,2,50.0,100.0,api
5,1005,C004,Ana Pereira,07-01-2023,MONITOR,-,899.0,899.0,planilha
6,1006,C005,Pedro Santos,2023-01-08,MONITOR,1,899.0,899.0,NaN
7,1007,C006,Pedro Santos,2023-01-08,CADEIRA GAMER,1,1200.5,1200.5,erp
8,1008,C006,Pedro Santos,2023-01-08,CADEIRA GAMER,1,1200.5,1200.5,erp
9,1009,C007,Marcos Oliveira,2023-01-08,TECLADO,2,120.0,240.0,NaN

In [ ]:
df["sistema_origem"] = df["sistema_origem"].fillna("outro")
df

/tmp/ipykernel_1823/3926972062.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["sistema_origem"] = df["sistema_origem"].fillna("outro")

,id_pedido,id_cliente,nome,data,produto,quantidade,preco,total,sistema_origem
0,1001,C001,João Silva,2023-01-05,NOTEBOOK,1,3500.0,3500.0,erp
1,1002,C002,Maria Souza,05/01/2023,MOUSE,2,50.0,100.0,erp
2,1003,C002,Maria Souza,2023/01/06,MOUSE,2,50.0,100.0,api
3,1003,C002,Maria Souza,2023/01/06,MOUSE,2,50.0,100.0,api
5,1005,C004,Ana Pereira,07-01-2023,MONITOR,-,899.0,899.0,planilha
6,1006,C005,Pedro Santos,2023-01-08,MONITOR,1,899.0,899.0,outro
7,1007,C006,Pedro Santos,2023-01-08,CADEIRA GAMER,1,1200.5,1200.5,erp
8,1008,C006,Pedro Santos,2023-01-08,CADEIRA GAMER,1,1200.5,1200.5,erp
9,1009,C007,Marcos Oliveira,2023-01-08,TECLADO,2,120.0,240.0,outro

In [ ]:
df["quantidade"][0] = "-"
df

/tmp/ipykernel_1823/1203646210.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df["quantidade"][0] = "-"
/tmp/ipykernel_1823/1203646210.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["quantidade"][0] = "-"

,id_pedido,id_cliente,nome,data,produto,quantidade,preco,total,sistema_origem
0,1001,C001,João Silva,2023-01-05,NOTEBOOK,-,3500.0,3500.0,erp
1,1002,C002,Maria Souza,05/01/2023,MOUSE,2,50.0,100.0,erp
2,1003,C002,Maria Souza,2023/01/06,MOUSE,2,50.0,100.0,api
3,1003,C002,Maria Souza,2023/01/06,MOUSE,2,50.0,100.0,api
5,1005,C004,Ana Pereira,07-01-2023,MONITOR,-,899.0,899.0,planilha
6,1006,C005,Pedro Santos,2023-01-08,MONITOR,1,899.0,899.0,outro
7,1007,C006,Pedro Santos,2023-01-08,CADEIRA GAMER,1,1200.5,1200.5,erp
8,1008,C006,Pedro Santos,2023-01-08,CADEIRA GAMER,1,1200.5,1200.5,erp
9,1009,C007,Marcos Oliveira,2023-01-08,TECLADO,2,120.0,240.0,outro

In [ ]:
# Iremos trabalhar com a quantidade agora!
# info diz que quantidade é object, vamos converter para número
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9 entries, 0 to 9
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id_pedido       9 non-null      int64
 1   id_cliente      9 non-null      object
 2   nome            9 non-null      object
 3   data            9 non-null      object
 4   produto         9 non-null      object
 5   quantidade      9 non-null      object
 6   preco           9 non-null      float64
 7   total           9 non-null      float64
 8   sistema_origem  9 non-null      object
dtypes: float64(2), int64(1), object(6)
memory usage: 1020.0+ bytes

In [ ]:
df["quantidade"] = pd.to_numeric(df["quantidade"], errors="coerce")
df

/tmp/ipykernel_1823/783094403.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["quantidade"] = pd.to_numeric(df["quantidade"], errors="coerce")

,id_pedido,id_cliente,nome,data,produto,quantidade,preco,total,sistema_origem
0,1001,C001,João Silva,2023-01-05,NOTEBOOK,NaN,3500.0,3500.0,erp
1,1002,C002,Maria Souza,05/01/2023,MOUSE,2.0,50.0,100.0,erp
2,1003,C002,Maria Souza,2023/01/06,MOUSE,2.0,50.0,100.0,api
3,1003,C002,Maria Souza,2023/01/06,MOUSE,2.0,50.0,100.0,api
5,1005,C004,Ana Pereira,07-01-2023,MONITOR,NaN,899.0,899.0,planilha
6,1006,C005,Pedro Santos,2023-01-08,MONITOR,1.0,899.0,899.0,outro
7,1007,C006,Pedro Santos,2023-01-08,CADEIRA GAMER,1.0,1200.5,1200.5,erp
8,1008,C006,Pedro Santos,2023-01-08,CADEIRA GAMER,1.0,1200.5,1200.5,erp
9,1009,C007,Marcos Oliveira,2023-01-08,TECLADO,2.0,120.0,240.0,outro

In [ ]:
# Vendo info novamente, percebemos que a conversão foi feita!
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9 entries, 0 to 9
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id_pedido       9 non-null      int64
 1   id_cliente      9 non-null      object
 2   nome            9 non-null      object
 3   data            9 non-null      object
 4   produto         9 non-null      object
 5   quantidade      7 non-null      float64
 6   preco           9 non-null      float64
 7   total           9 non-null      float64
 8   sistema_origem  9 non-null      object
dtypes: float64(3), int64(1), object(5)
memory usage: 1020.0+ bytes

Função para formatar um valor de data aplicando mais de uma máscara de formatação:

In [ ]:
def parse_data(valor):
  formatos = ["%Y-%m-%d", "%d/%m/%Y"]
  for formato in formatos:
    try:
      return pd.to_datetime(valor, format=formato)
    except:
      pass
    return pd.NaT

Aplicar a função **parse_data**

In [ ]:
df['data'] = df['data'].apply(parse_data)
df = df.dropna(subset="data")
df

/tmp/ipykernel_1823/3164073501.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['data'] = df['data'].apply(parse_data)

,id_pedido,id_cliente,nome,data,produto,quantidade,preco,total,sistema_origem
6,1006,C005,Pedro Santos,2023-01-08,MONITOR,1.0,899.0,899.0,outro
7,1007,C006,Pedro Santos,2023-01-08,CADEIRA GAMER,1.0,1200.5,1200.5,erp
8,1008,C006,Pedro Santos,2023-01-08,CADEIRA GAMER,1.0,1200.5,1200.5,erp
9,1009,C007,Marcos Oliveira,2023-01-08,TECLADO,2.0,120.0,240.0,outro

Removendo linhas duplicadas (por exemplo linhas 2 e 3)

In [ ]:
df = df.drop_duplicates()
df

,id_pedido,id_cliente,nome,data,produto,quantidade,preco,total,sistema_origem
6,1006,C005,Pedro Santos,2023-01-08,MONITOR,1.0,899.0,899.0,outro
7,1007,C006,Pedro Santos,2023-01-08,CADEIRA GAMER,1.0,1200.5,1200.5,erp
8,1008,C006,Pedro Santos,2023-01-08,CADEIRA GAMER,1.0,1200.5,1200.5,erp
9,1009,C007,Marcos Oliveira,2023-01-08,TECLADO,2.0,120.0,240.0,outro

## Exercícios
a) Criar um pivotamento para exibir o cruzamento entre o total de compra por cliente e sistema de origem
conforme abaixo

In [ ]:
pd.pivot_table(
    df,
    values = 'total',
    index = 'id_cliente',
    columns = 'sistema_origem',
    aggfunc = 'sum',
    fill_value = 0
)

sistema_origem     erp  outro
id_cliente
C005               0.0  899.0
C006            2401.0    0.0
C007               0.0  240.0

In [ ]:
df_filtered = df[df['sistema_origem'] != 'outro']
pd.pivot_table(
    df_filtered,
    values = 'total',
    index = 'id_cliente',
    columns = 'sistema_origem',
    aggfunc = 'sum',
    fill_value = 0
)

sistema_origem     erp
id_cliente
C006            2401.0